name = "spectra-grid"
main = ".open-next/worker.js"
compatibility_date = "2025-06-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "photos"

[[d1_databases]]
binding = "DB"
database_name = "photo_meta"
database_id = "cfc74ead-6694-438f-b96f-9c77fc90c555"

[vars]
GRID_W = "240"
GRID_H = "240" 